### ISSUE TITLE
CSV file support

### ISSUE THREAD

**Issue by saurav-dhait** [AI-Guru/helibrunna#1]
Hello,

I’m new to xLSTM and would like to use it for time series forecasting. Could you please guide me on how to approach this using Helibrunna?

Thank you in advance for your assistance.

**Comment by AI-Guru** [comment]
Hi! 

Welcome to the world of xLSTM.

Great question!

Helibrunna is made for Causal Language Modeling, aka next-token prediction a la GPT. Thus it is in the field of NLP.

That said, I do not see a problem adapting the code for time-series. Here would be the steps:

- Replace the text data loading functionality with a data loader that yields multi-variate time series segments as inputs and target values as output.

- Change the model architecture. Remove the input embedding layer. Replace the last fully connected layer with global pooling and a linear layer.

That should do the trick!

**Comment by saurav-dhait** [comment]
I will try it.
Thankyou for your response.

**Comment by AI-Guru** [comment]
@saurav-dhait start here: https://arxiv.org/abs/2407.10240
